// Decompiled with JetBrains decompiler
// Type: System.Deployment.Application.Constants
// Assembly: System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 3325BD7A-5C2D-4917-8EF5-AD0E0DDAE2E8
// Assembly location: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Deployment.dll

namespace System.Deployment.Application
{
  internal static class Constants
  {
    public static Guid DeploymentPropertySet = new Guid("2ad613da-6fdb-4671-af9e-18ab2e4df4d8");
    public static TimeSpan OnlineAppScavengingGracePeriod = TimeSpan.FromMinutes(1.0);
    public static Version V2CLRVersion = new Version("2.0.50727.0");
    public static Version V4CLRVersion = new Version("4.0");
    public static TimeSpan LockTimeout = TimeSpan.FromMinutes(2.0);
    public static TimeSpan AssertApplicationRequirementsTimeout = TimeSpan.FromMinutes(2.0);
    public static Guid CLSID_StartMenuPin = new Guid("A2A9545D-A0C2-42B4-9708-A0B2BADD77C8");
    public static Guid IID_IUnknown = new Guid("00000000-0000-0000-C000-000000000046");
    public static Guid uuid = new Guid("43826d1e-e718-42ee-bc55-a1e261c37bfe");
    public const string ShimDll = "dfshim.dll";
    public const string DfDll = "dfdll.dll";
    public const string DeploymentFolder = "Deployment";
    public const string Dfsvc = "dfsvc.exe";
    public const string SystemDeploymentDll = "system.deployment.dll";
    public const string Kernel32Dll = "kernel32.dll";
    public const string MscoreeDll = "mscoree.dll";
    public const string WininetDll = "wininet.dll";
    public const string ClrDll = "clr.dll";
    public const string SrClientDll = "srclient.dll";
    public const string WinInetDll = "wininet.dll";
    public const string Shell32Dll = "shell32.dll";
    public const string ShellAppShortcutExtension = ".appref-ms";
    public const string ShellSupportShortcutExtension = ".url";
    public const int SupportIconIndex = 0;
    public const int ShortCutRemovalRetryTimes = 2;
    public const int ShortCutRemovalRetryInternal = 1000;
    public const string UninstallSubkeyName = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall";
    public const string DeploymentSubkeyName = "SOFTWARE\\Classes\\Software\\Microsoft\\Windows\\CurrentVersion\\Deployment";
    public const string LUAPolicyKeyName = "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
    public const string OnlineAppQuotaInKBValueName = "OnlineAppQuotaInKB";
    public const string OnlineAppQuotaUsageEstimateValueName = "OnlineAppQuotaUsageEstimate";
    public const string LUAPolicyValueName = "EnableLUA";
    public const string ClassesSubKeyName = "Software\\Classes";
    public const string AppIdValueName = "AppId";
    public const string DPUrlValueName = "DeploymentProviderUrl";
    public const string IconFileValueName = "IconFile";
    public const string ContentTypeValueName = "Content Type";
    public const string ShellKeyName = "shell";
    public const string OpenCommandKeyName = "open\\command";
    public const string IconHandlerKeyName = "shellex\\IconHandler";
    public const string CLSIDKeyName = "CLSID";
    public const string InProcServerKeyName = "InProcServer32";
    public const string GuidValueName = "Guid";
    public const string RootKeyName = "Software\\Microsoft\\.NETFramework\\DeploymentFramework";
    public const string RequireSignedManifests = "RequireSignedManifests";
    public const string RequireHashInManifests = "RequireHashInManifests";
    public const string SkipSignatureValidationValueName = "SkipSignatureValidation";
    public const string SkipDeploymentProviderValueName = "SkipDeploymentProvider";
    public const string SkipSchemaValidationValueName = "SkipSchemaValidation";
    public const string SkipSemanticValidationValueName = "SkipSemanticValidation";
    public const string SkipApplicationDependencyHashCheckValueName = "SkipApplicationDependencyHashCheck";
    public const string SuppressLimitOnNumberOfActivationsValueName = "SuppressLimitOnNumberOfActivations";
    public const string DisableGenericExceptionHandler = "DisableGenericExceptionHandler";
    public const string LogVerbosityLevel = "LogVerbosityLevel";
    public const string DeploymentManifestSuffix = ".application";
    public const string ManifestSuffix = ".manifest";
    public const string DllSuffix = ".dll";
    public const string ExeSuffix = ".exe";
    public const string MapFileExtensionsSuffix = ".deploy";
    public const string InstallReferenceIdentifier = "{3f471841-eef2-47d6-89c0-d028f03a4ad5}";
    public const string SubscriptionStoreLock = "__SubscriptionStoreLock__";
    public const string IsShellVisible = "IsShellVisible";
    public const string CurrentBind = "CurrentBind";
    public const string PreviousBind = "PreviousBind";
    public const string PendingBind = "PendingBind";
    public const string ExcludedDeployment = "ExcludedDeployment";
    public const string PendingDeployment = "PendingDeployment";
    public const string DeploymentProviderUri = "DeploymentProviderUri";
    public const string MinimumRequiredVersion = "MinimumRequiredVersion";
    public const string LastCheckTime = "LastCheckTime";
    public const string UpdateSkipTime = "UpdateSkipTime";
    public const string UpdateSkippedDeployment = "UpdateSkippedDeployment";
    public const string AppType = "AppType";
    public const string UseApplicationManifestDescription = "UseApplicationManifestDescription";
    public const string DeploymentSourceUri = "DeploymentSourceUri";
    public const string ApplicationSourceUri = "ApplicationSourceUri";
    public const string IsFullTrust = "IsFullTrust";
    public const string CLRCoreComp = "Microsoft-Windows-CLRCoreComp";
    public const string CommonLanguageRuntime = "Microsoft.Windows.CommonLanguageRuntime";
    public const uint MinVersionCLRMajor = 2;
    public const string MSIL = "msil";
    public const string X86 = "x86";
    public const string AMD64 = "amd64";
    public const string IA64 = "ia64";
    public const string AsmV1Namespace = "urn:schemas-microsoft-com:asm.v1";
    public const string AsmV2Namespace = "urn:schemas-microsoft-com:asm.v2";
    public const string XmlDSigNamespace = "http://www.w3.org/2000/09/xmldsig#";
    public const string AdaptiveSchemaResourceName = "manifest.2.0.0.15-pre.adaptive.xsd";
    public const string PublicIdForDTD4XMLSchemas = "-//W3C//DTD XMLSCHEMA 200102//EN";
    public const string XMLSchemaDTDResourceName = "XMLSchema.dtd";
    public const string PublicIdForDTD4DataTypes = "xs-datatypes";
    public const string DataTypesDTDResourceName = "datatypes.dtd";
    public const string UnsignedPublicKeyToken = "0000000000000000";
    public const string RequireAdministrator = "requireAdministrator";
    public const string HighestAvailable = "highestAvailable";
    public const int MaxNumberOfFilesInApplication = 24576;
    public const int MaxNumberOfFileAssociationsInApplication = 8;
    public const int MaxNumberOfFileExtensionLength = 24;
    public const int MaxNumberOfAssembliesInApplication = 24576;
    public const int MaxNumberOfGroupsInApplication = 49152;
    public const int MaxUrlLength = 16384;
    public const int MaxLiveActivation = 8;
    public const int MaxIdentityLength = 2048;
    public const int MaxAppIdLength = 65536;
    public const int MaxShortcutFileSize = 65536;
    public const int MaxManifestFileSize = 16777216;
    public const int MaxValueForMaximumAge = 365;
    public const int MaxErrorUrlLength = 2048;
    public const uint DefaultOnlineAppQuotaInKB = 256000;
    public const int LifetimeDefaultMinutes = 10;
    public const int LockRetryIntervalMs = 1;
    public const int MinProgressCallbackIntervalInMs = 100;
    public const string DefaultLogTextualId = "__DeploymentDefaultLogFile__";
    public const int MAX_PATH = 260;
    public const string LogFileExtension = "log";
    public const string LogFilePathRegistryString = "LogFilePath";
    public const string WininetCacheLogUrlPrefix = "System_Deployment_Log_";
    public const string GACDetectionTempManifestAsmIdText = "GACDetectionTempManifest, version=1.0.0.0, type=win32";
    public const string DataDirectory = "DataDirectory";
    public const int HRESULT_DiskFull = -2147024784;
    public const uint MASK_NOTPINNABLE = 2147483648;
    public const uint MASK_DONT_SHOW_INSTALL_DIALOG = 256;
    public const string Client35SP1SignatureAssembly = "Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a,processorArchitecture=msil";
    public const string Full35SP1SignatureAssembly = "System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089,processorArchitecture=msil";
    public const string DotNetFX35SP1 = ".NET Framework 3.5 SP1";
    public const string SkipSKUDetectionKeyName = "SOFTWARE\\Microsoft\\Fusion";
    public const string SkipSKUDetectionValueName = "NoClientChecks";
    public const string SetupKeyCommonPath = "SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v";
    public const string PreV4ClientSetupKeyCommonPath = "SOFTWARE\\Microsoft\\NET Framework Setup\\DotNetClient\\v";
    public const string V30SetupKeyPath = "SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v3.0\\Setup";
    public const string NetFxKeyCommonPath = "SOFTWARE\\Microsoft\\.NETFramework\\v";
    public const string TFMFormatNoProfile = ".NETFramework,Version=v{0}";
    public const string TFMFormatWithProfile = ".NETFramework,Version=v{0},Profile={1}";
    public const string FullProfileName = "Full";
    public const string PreV4ClientProfileName = "Client";
    public const string PreV4SetupValueName = "Version";
    public const string V4SetupValueName = "TargetVersion";
    public const string InstallValueName = "Install";
    public const string V30InstallValueName = "InstallSuccess";
    public const string FrameworkGroupName = "framework";
    public const int CLSCTX_INPROC_SERVER = 1;
  }
}
