// Decompiled with JetBrains decompiler
// Type: System.Deployment.Internal.Isolation.Manifest.CMS_REGISTRY_VALUE_TYPE
// Assembly: System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 3325BD7A-5C2D-4917-8EF5-AD0E0DDAE2E8
// Assembly location: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Deployment.dll

namespace System.Deployment.Internal.Isolation.Manifest
{
  internal enum CMS_REGISTRY_VALUE_TYPE
  {
    CMS_REGISTRY_VALUE_TYPE_NONE,
    CMS_REGISTRY_VALUE_TYPE_SZ,
    CMS_REGISTRY_VALUE_TYPE_EXPAND_SZ,
    CMS_REGISTRY_VALUE_TYPE_MULTI_SZ,
    CMS_REGISTRY_VALUE_TYPE_BINARY,
    CMS_REGISTRY_VALUE_TYPE_DWORD,
    CMS_REGISTRY_VALUE_TYPE_DWORD_LITTLE_ENDIAN,
    CMS_REGISTRY_VALUE_TYPE_DWORD_BIG_ENDIAN,
    CMS_REGISTRY_VALUE_TYPE_LINK,
    CMS_REGISTRY_VALUE_TYPE_RESOURCE_LIST,
    CMS_REGISTRY_VALUE_TYPE_FULL_RESOURCE_DESCRIPTOR,
    CMS_REGISTRY_VALUE_TYPE_RESOURCE_REQUIREMENTS_LIST,
    CMS_REGISTRY_VALUE_TYPE_QWORD,
    CMS_REGISTRY_VALUE_TYPE_QWORD_LITTLE_ENDIAN,
  }
}
